In [11]:
# importing Pandas
import pandas as pd

#loading the Dataset into pandas
df=pd.read_csv(r'C:\Users\Sirlaw\Desktop\Data Science Project\sales_data.csv')

In [12]:
#checking the First five rows of the dataset
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [13]:
#checking the last five rows of the dataset
df.tail()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [14]:
#checking for shape
df.shape

(1000, 14)

In [15]:
#Overall Dataset Info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   str
 2   Sales_Rep             1000 non-null   str
 3   Region                1000 non-null   str
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   str
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   str
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   str
 12  Sales_Channel         1000 non-null   str
 13  Region_and_Sales_Rep  1000 non-null   str
dtypes: float64(4), int64(2), str(8)
memory usage: 109.5 KB

In [16]:
#correcting datatype for Date solumn

In [17]:
#Checking for missing values
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [18]:
#checking for duplicates
df.duplicated().sum()

np.int64(0)

In [19]:
#summary statistics of Numerical feautures
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

In [20]:
# selecting the sales Column
df["Sales_Amount"]

0      5053.97
1      4384.02
2      4631.23
3      2167.94
4      3750.20
        ...
995    4733.88
996    4716.36
997    7629.70
998    1629.47
999    4923.93
Name: Sales_Amount, Length: 1000, dtype: float64

In [39]:
#Filtering Sales Greater than 1000
Filtered_Data=df[df["Sales_Amount"] > 1000]
Filtered_Data.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [40]:
#Filtering Products Sold in The Northan Region
df[df["Region"] == "North"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
15,1053,2023-10-16,Bob,North,2235.83,48,Furniture,121.19,487.65,New,0.18,Cash,Retail,North-Bob
16,1002,2023-05-30,David,North,6810.35,17,Furniture,4024.76,4420.15,Returning,0.04,Cash,Online,North-David
20,1002,2023-04-22,Eve,North,6551.23,9,Electronics,4398.16,4439.12,New,0.18,Bank Transfer,Online,North-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,1090,2023-01-04,Eve,North,1028.39,14,Furniture,4037.21,4323.71,Returning,0.27,Credit Card,Online,North-Eve
988,1044,2023-08-08,Alice,North,4912.69,18,Clothing,430.14,641.18,New,0.13,Cash,Online,North-Alice
993,1025,2023-06-26,David,North,2457.65,47,Furniture,3861.61,3998.91,New,0.25,Credit Card,Online,North-David
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob

In [41]:
# filtering Online Sales Only
df[df["Sales_Channel"] == "Online"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,1025,2023-06-26,David,North,2457.65,47,Furniture,3861.61,3998.91,New,0.25,Credit Card,Online,North-David
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [42]:
#Filtering with Multiple Conditions
df[
    (df["Product_Category"] == "Electronics") &
    (df["Sales_Amount"] > 1000)
]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
17,1088,2023-10-04,Bob,East,6116.75,40,Electronics,4904.93,5034.35,New,0.10,Credit Card,Retail,East-Bob
20,1002,2023-04-22,Eve,North,6551.23,9,Electronics,4398.16,4439.12,New,0.18,Bank Transfer,Online,North-Eve
21,1064,2023-01-04,Eve,East,7412.11,10,Electronics,4764.96,5074.42,New,0.12,Cash,Online,East-Eve
27,1022,2023-06-01,David,East,8913.13,9,Electronics,2263.65,2558.95,New,0.03,Cash,Online,East-David
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,1018,2023-08-31,Alice,East,2260.25,1,Electronics,2315.83,2333.19,New,0.01,Cash,Retail,East-Alice
978,1015,2023-07-26,David,North,2706.15,9,Electronics,4680.35,4758.11,Returning,0.05,Bank Transfer,Online,North-David
985,1017,2023-01-24,Eve,North,4637.40,27,Electronics,927.89,1399.09,Returning,0.27,Credit Card,Online,North-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David

In [43]:
#Select Rows and Columns Together

#Display only the region, sales amount, and quantity sold for online orders:

df.loc[
    df["Sales_Channel"] == "Online",
    ["Region", "Sales_Amount", "Quantity_Sold"]
]

    Region  Sales_Amount  Quantity_Sold
0    North       5053.97             18
4     East       3750.20             13
5     West       3761.15             32
6     West        618.31             29
7    South       7698.92             46
..     ...           ...            ...
993  North       2457.65             47
995  North       4733.88              4
997  South       7629.70             17
998   West       1629.47             39
999   East       4923.93             48

[488 rows x 3 columns]

In [44]:
#Slice Subsets Using .iloc
#First 10 rows
df.iloc[:10]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie

In [45]:
#First 5 rows and first 4 columns
df.iloc[:5, :4]

   Product_ID   Sale_Date Sales_Rep Region
0        1052  2023-02-03       Bob  North
1        1093  2023-04-21       Bob   West
2        1015  2023-09-21     David  South
3        1072  2023-08-24       Bob  South
4        1061  2023-03-24   Charlie   East

In [46]:
#Rows 50–100 and columns 2–6
df.iloc[50:101, 2:7]

    Sales_Rep Region  Sales_Amount  Quantity_Sold Product_Category
50      Alice   East       3187.45             11         Clothing
51        Eve  South       7762.51             39      Electronics
52      David  North       7751.92             43        Furniture
53    Charlie   West       5260.83             31      Electronics
54      David   West       9762.54             17             Food
55      Alice  North       1342.95             33         Clothing
56      Alice   West        267.78             32      Electronics
57      David   East       7724.57             29      Electronics
58      David   East       8090.84             21         Clothing
59      Alice   West       1290.05             21        Furniture
60    Charlie   East       2729.27             40      Electronics
61        Eve   East        273.77             23         Clothing
62        Eve   West       3003.76              6        Furniture
63      David  South       7754.10             22             Food
64        Eve  North       5227.81             38         Clothing
65      Alice   East       3546.15             37      Electronics
66      Alice  South       3780.22             45             Food
67      David   East        113.40              8        Furniture
68      David   East       3068.03             41        Furniture
69      David  North       6499.94             49         Clothing
70    Charlie   East       9744.52             35         Clothing
71        Eve  North       8485.90             11         Clothing
72      David  North        333.59             24        Furniture
73        Bob  North       8995.75             49             Food
74        Bob  South       7853.66             21        Furniture
75      Alice   West       7825.72              2      Electronics
76        Eve  South       4634.16             40        Furniture
77      David   West       4040.25             19      Electronics
78        Bob   West       3098.87             39             Food
79        Eve  North        750.38             28         Clothing
80      Alice   East       2359.53             17         Clothing
81    Charlie  North       2541.38              6        Furniture
82        Eve   East       4892.36             19         Clothing
83        Eve   West       7499.70             38             Food
84    Charlie  North       4790.72             28         Clothing
85        Eve   East        672.66              2        Furniture
86      Alice  South       9582.12             38             Food
87      Alice   East       9432.97             37      Electronics
88    Charlie  North       7873.38              4        Furniture
89      David  South       9914.15             22      Electronics
90        Bob   East       5490.38             26             Food
91      David   East       9631.41             49        Furniture
92        Eve   East        848.49             43        Furniture
93        Bob   East       3720.24             36             Food
94    Charlie   East       2331.27             13         Clothing
95    Charlie  South       2038.75             32        Furniture
96        Bob   West       1493.95             17        Furniture
97      Alice  South       6261.90             41      Electronics
98        Bob  South       7835.09             36         Clothing
99        Eve  South       5825.15             46      Electronics
100     Alice   West       1554.93             19      Electronics

In [47]:
#Sort Data
#Highest sales
df.sort_values(by="Sales_Amount", ascending=False).head(10)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
755,1036,2023-12-10,David,North,9989.04,7,Food,2882.25,3163.70,Returning,0.05,Cash,Retail,North-David
760,1050,2023-08-21,David,North,9976.52,17,Furniture,2346.80,2654.65,New,0.13,Cash,Retail,North-David
855,1079,2023-08-24,Alice,North,9972.66,8,Clothing,3808.23,3891.62,Returning,0.26,Bank Transfer,Online,North-Alice
654,1075,2023-08-15,Charlie,North,9972.11,28,Clothing,2570.22,2610.84,Returning,0.27,Bank Transfer,Retail,North-Charlie
748,1016,2023-04-23,David,South,9961.96,6,Furniture,4502.09,4879.72,New,0.13,Credit Card,Online,South-David
796,1063,2023-08-14,Bob,North,9956.75,27,Clothing,3760.25,4147.11,New,0.22,Cash,Online,North-Bob
142,1099,2023-04-14,Alice,East,9948.71,27,Food,4929.55,4990.33,Returning,0.29,Credit Card,Online,East-Alice
189,1089,2023-10-19,Eve,West,9933.22,23,Food,2120.54,2597.67,Returning,0.26,Credit Card,Retail,West-Eve
89,1015,2023-09-22,David,South,9914.15,22,Electronics,4275.59,4576.72,Returning,0.02,Cash,Retail,South-David
784,1010,2023-10-12,Charlie,North,9907.72,20,Furniture,4298.74,4475.19,Returning,0.16,Cash,Online,North-Charlie

In [48]:
#Largest discount
df.sort_values(by="Discount", ascending=False).head(10)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
442,1062,2023-11-06,David,East,2605.71,25,Food,2361.05,2616.19,New,0.3,Bank Transfer,Retail,East-David
292,1012,2023-11-14,Eve,North,519.98,6,Clothing,3609.42,4082.62,Returning,0.3,Bank Transfer,Retail,North-Eve
52,1089,2023-10-27,David,North,7751.92,43,Furniture,3851.45,4186.98,Returning,0.3,Credit Card,Online,North-David
566,1095,2023-11-07,Charlie,West,6970.10,32,Clothing,4266.64,4523.36,New,0.3,Bank Transfer,Retail,West-Charlie
867,1082,2023-07-28,Alice,East,8540.22,48,Food,3380.52,3778.94,Returning,0.3,Bank Transfer,Online,East-Alice
504,1086,2023-02-26,Bob,West,2559.00,5,Electronics,4934.10,5191.02,New,0.3,Bank Transfer,Online,West-Bob
883,1029,2023-08-02,Eve,South,2855.85,46,Furniture,4609.66,4879.15,Returning,0.3,Cash,Retail,South-Eve
645,1042,2023-08-29,Eve,South,3955.11,27,Clothing,1139.45,1454.41,Returning,0.3,Bank Transfer,Online,South-Eve
372,1099,2023-10-20,David,South,7859.22,23,Clothing,93.45,181.62,Returning,0.3,Bank Transfer,Retail,South-David
33,1092,2023-02-09,David,West,2749.17,34,Furniture,2037.41,2238.65,New,0.3,Credit Card,Online,West-David

In [49]:
#Filter Using .isin()

#Orders from North and South regions:

df[df["Region"].isin(["North", "South"])]

# Filter by Sales Representative
df[df["Sales_Rep"] == "Bob"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
11,1100,2023-08-14,Bob,West,2198.74,43,Food,1100.81,1137.44,Returning,0.08,Bank Transfer,Online,West-Bob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,1056,2023-12-27,Bob,East,7979.67,4,Food,1612.82,1647.25,Returning,0.04,Credit Card,Retail,East-Bob
981,1028,2023-11-01,Bob,East,7946.69,24,Food,911.11,1214.56,New,0.22,Bank Transfer,Online,East-Bob
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
990,1017,2023-01-20,Bob,East,496.59,29,Clothing,3410.49,3481.72,New,0.24,Bank Transfer,Retail,East-Bob
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob

In [50]:
#Creating a Subset Called online_electronics
#Suppose I want to analyze online electronics sales:

online_electronics = df[
    (df["Sales_Channel"] == "Online") &
    (df["Product_Category"] == "Electronics")
]

online_electronics.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
20,1002,2023-04-22,Eve,North,6551.23,9,Electronics,4398.16,4439.12,New,0.18,Bank Transfer,Online,North-Eve
21,1064,2023-01-04,Eve,East,7412.11,10,Electronics,4764.96,5074.42,New,0.12,Cash,Online,East-Eve
27,1022,2023-06-01,David,East,8913.13,9,Electronics,2263.65,2558.95,New,0.03,Cash,Online,East-David
39,1047,2023-08-08,David,North,1331.25,33,Electronics,1341.55,1427.21,Returning,0.15,Credit Card,Online,North-David

In [51]:
#creating a Subset called Region_Amount
Region_Amount = df[["Product_ID", "Region", "Sales_Amount"]]
Region_Amount.head()

   Product_ID Region  Sales_Amount
0        1052  North       5053.97
1        1093   West       4384.02
2        1015  South       4631.23
3        1072  South       2167.94
4        1061   East       3750.20

In [52]:
Filtered_Data.to_csv('Filtered_Data.csv',index=False)

In [53]:
import os
print(os.getcwd())

g:\My Drive\Colab Notebooks